name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ios: [ "13.1", "13.2", "13.3" ]
        include:
          - ios: "13.1"
            xcode: "XCode_11.1"
          - ios: "13.2"
            xcode: "XCode_11.2"
          - ios: "13.3"
            xcode: "XCode_11.3"
    steps:
    - uses: actions/checkout@master
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: Example/SwiftTypedRouter.xcworkspace
        scheme: SwiftTypedRouter-Example
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
        additional_lint_params: --private
        use_modern_build_system: true
