name: CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [ XCode_11, XCode_11_3 ]
        ios: [ 13.0, 13.1, 13.2, 13.3 ]
        exclude:
          - xcode: XCode_11
            ios: 13.1
          - xcode: XCode_11
            ios: 13.2
          - xcode: XCode_11
            ios: 13.3
          - xcode: XCode_11_3
            ios: 13.0
          - xcode: XCode_11_3
            ios: 13.1
    steps:
    - uses: actions/checkout@master
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: Example/SwiftTypedRouter.xcworkspace
        scheme: SwiftTypedRouter-Example
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
        additional_lint_params: --private
        use_modern_build_system: true
